server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: booking-service
            uri: lb://booking-service
            predicates:
              - Path=/booking/{segment}
            filters:
              - SetPath=/{segment}

          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/user/{segment}
            filters:
              - SetPath=/{segment}

          - id: tour-service
            uri: lb://tour-service
            predicates:
              - Path=/tour/{segment}
            filters:
              - SetPath=/{segment}

          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/payment/{segment}
            filters:
              - SetPath=/{segment}

          - id: report-service
            uri: lb://report-service
            predicates:
              - Path=/report/{segment}
            filters:
              - SetPath=/{segment}
