server:
  port: 8001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
      routes:
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: tour-service
          uri: lb://TOUR-SERVICE
          predicates:
            - Path=/tour/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/report/**
